### ISSUE TITLE
10. As an item, I want my estimated next purchase date to be computed at the time my purchase is recorded in the database

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-7-smart-shopping-list#11]
AC:

* When a purchase is recorded, the estimated number of days until the next purchase date should be calculated and recorded in the database

The following script can be used to calculate the estimated next purchase date: https://gist.github.com/segdeha/a45ef8d6d7f094f4038a2318a9d60051

**Comment by nabilkaz** [comment]
**Problem:**
1. A purchase date is recorded
2. A next purchase date is calculated using the gist code which requires the frequency value.
3. These are stored as key-value pairs in the corresponding firebase document

**Comment by nabilkaz** [comment]
Branch created: `NK-TC-estimated-next-purchase-date`

**Comment by nabilkaz** [comment]
Per the discussion yesterday - 
The intended behavior is:
* Items are not allowed to be unchecked
* when checked new item data is sent to the server and updates document (as described below)
```javascript
{
    purchaseFrequency: // calcEstimate(oldFrequency, today-lastPurchaseDate, numberOfPurchases)
    lastPurchasedDate: // today,
    nextPurchaseDate: // purchaseFrequency + today,
    numberOfPurchases: // numberOfPurchases + 1,
}
```
