### ISSUE TITLE
13. As a user, I want to view details of my purchases to better understand my purchase patterns

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-7-smart-shopping-list#14]
AC:

* From the shopping list, user can tap to navigate to a detailed view of the item
* Detail view includes the following information:
  * Name of the item
  * Last purchased date
  * Estimated number of days until the next purchase
  * Number of times the item has been purchased"
* When in the “item details” view, a back arrow should appear in the header that takes the user back to the “list” view

**Comment by nabilkaz** [comment]
Here is the breakdown of the issue:
1. Dynamic route for each item
2. Clickable item in item list that routes to items detail page
3. Unique item detail page with item details
4. Top navigation with back button

**Comment by nabilkaz** [comment]
Strategy for creating unique pages for each item.
1. Grab the document id
2. Use it as part of the URL path
3. Create a route that will recognize the document id in the URL path and pass that information to a react component that will pull the item information in.

**Comment by nabilkaz** [comment]
Running into an issue with the latest merge to master. Seems like everything is broken.

**Comment by DeeThompson** [comment]
We are still having an issue with the latest Merge, there seems to be open tags and pieces of code that are duplicated, however we need to do a 'deeper dive' as far as a code review. Currently when running from localhost the app fails to compile.
