### ISSUE TITLE
1. As a component, I want to be able to read from and write to the Firestore database

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-7-smart-shopping-list#2]
This is 1 of 2 stories that should be finished in the first week in order to enable further development.

AC:

* The following have been added as project dependencies: firebase & react-firestore
* Make a change in the Firestore database and it shows up in the app
* Make a change in the app and it shows up in the Firestore database

**Comment by msholty-fd** [comment]
You can find out more info about `react-firestore` here: https://github.com/green-arrow/react-firestore

**Comment by msholty-fd** [comment]
Here's a link to our Firebase dashboard: https://console.firebase.google.com/u/1/project/tcl-7-smart-shopping-list/overview

**Comment by meganmckissack** [comment]
To do list:

- [x] add firebase & react-firestore dependencies 

- [x] import Firestore Provide to index.js

- [x] create new Firebase collection for grocery items

- [ ] create Firestore Collection component

- [x] create Firestore Document component

- [x] test that data can be fetched from and added to firebase
