### ISSUE TITLE
2. As a user, I want to be able to navigate between the “list” view and the “add an item” view

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-7-smart-shopping-list#3]
This is 1 of 2 stories that should be completed in the first week to enable further development of the app.

AC:

* `react-router-dom` has been added as a project dependency
* 2 tabs are present and persistent at the bottom of the app: one for the “list” view, the other for the “add an item” view
* When a link is clicked, the browser URL updates to represent the current view
* Whichever tab is selected should indicate somehow that it is selected

**Comment by stacietaylorcima** [comment]
1. Look at app see how it functions
2. take screenshots and breakdown UI into components
3. Add the dependency 
4. Find react-router-dom docs and figure out to use it

**Comment by nabilkaz** [comment]
- [x] Look at app see how it functions
- [x] take screenshots and breakdown UI into components
- [x] Add the dependency
- [x] Find react-router-dom docs and figure out to use it

------

The app's functions are pretty straightforward. 
- You either start a new list or join an existing list via a code
- Grocery list has two states: empty or with items
    - A grocery list with items can be filtered by searching for items
    - A grocery list item can be clicked and viewed with all details
- the top nav has three states (not sure why): just logo, logo+share button, logo+share button+ back button.
- **the bottom navigation either routes to a page to view your shopping list or add a shopping list item** (this one is relevant to our project).


You can view the full breakdown [via Figma here](https://www.figma.com/file/ZFnNTxHRtEWLAxxipW3bkS/tcl-7-smart-shopping-list?node-id=0%3A1)

![tcl-7-smart-shopping-list-Flow](https://user-images.githubusercontent.com/3664197/80938312-728d7600-8d8d-11ea-9c42-068cadf6388c.png)

<img width="1086" alt="Screen Shot 2020-05-03 at 10 32 07 PM" src="https://user-images.githubusercontent.com/3664197/80938442-f9dae980-8d8d-11ea-80ba-7c6cb22867c1.png">

**Comment by nabilkaz** [comment]
- [X]  Look at app see how it functions
- [X]  take screenshots and breakdown UI into components
- [x]  Add the dependency
- [X]  Find react-router-dom docs and figure out to use it

-----

Documentation and walkthrough for `react-router-dom`:
NPM listing
https://www.npmjs.com/package/react-router-dom

Git repo
https://github.com/ReactTraining/react-router

Intro video on using React Router from creators (9min)
https://reacttraining.com/react-router/

Quickstart
https://reacttraining.com/react-router/web/guides/quick-start

**Comment by nabilkaz** [comment]
Pair programming todos
Project breakdown:
- [x] Add dependency
- [x] Create two links that point to different URLs based on routes
- [x] Create tab navigation that sticks to the bottom
- [x] Create tab navigation that indicates which is selected

**Comment by nabilkaz** [comment]
Replaced the `Link` with `NavLink` module from the `react-router-dom` library. It allows us to assign classes when a link is clicked which makes it easier to satisfy this AC `Whichever tab is selected should indicate somehow that it is selected`. 

Documentation can be found here: https://reacttraining.com/react-router/web/api/NavLink

**Comment by nabilkaz** [comment]
Reviewed for accessibility issues and found 0. 
![image](https://user-images.githubusercontent.com/3664197/81221603-ebf8b480-8f97-11ea-8433-30c2cec3c0dd.png)

Also tabbing works across navigation
![image](https://user-images.githubusercontent.com/3664197/81221667-fb77fd80-8f97-11ea-98e3-a213131de7eb.png)

**Comment by nabilkaz** [comment]
All AC completed. 
Creating a PR for peer review
