### ISSUE TITLE
7. As a user, I want to see a welcoming prompt to add my first item if my list is empty to help me get oriented to how the app works

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-7-smart-shopping-list#8]
AC:

* The list view, when there are no items to display, should show a prompt (e.g., a button) for the user to add their first item

**Comment by nabilkaz** [comment]
Created branch `DT-NK-add-item-prompt`

**Comment by nabilkaz** [comment]
Decided to leverage the existing designs and add a header to the add item screen when the list is empty:

![image](https://user-images.githubusercontent.com/3664197/82918114-1e5b5900-9f29-11ea-8b6b-0c86a28928a8.png)
