### ISSUE TITLE
8. As a user, I want to mark an item on my shopping list as purchased

### ISSUE THREAD

**Issue by stacietaylorcima** [the-collab-lab/tcl-7-smart-shopping-list#9]
AC:

* User is able to tap a checkbox or similar UI element to mark an item in the list as purchased
* Item should be shown as checked for 24 hours after the purchase is made (i.e. we assume the user does not need to buy the item again for at least 1 day)

**Comment by meganmckissack** [comment]
Breakdown of tasks:

- [x] create checkbox functionality
- [ ] ~~import `lastPurchased` state from `addItem.js`~~
- [x] capture current date from checkbox entry indicating item is purchased ~~and update the database~~

- [x] create functionality to compare last purchased date with current date 
  - [x] if less than 24 hours after last purchased date : item stays checked
  - [x] if more than 24 hours after last purchased date : updated item to unchecked state
